export const mockProducts = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 99.99,
    image: "/images/model01.png",
    description: "Premium noise-cancelling headphones with 30h battery.",
    category: "Electronics",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 199.99,
    image: "/next.svg",
    description: "Fitness tracker with heart rate monitor and GPS.",
    category: "Electronics",
  },
  {
    id: 3,
    name: "Cotton T-Shirt",
    price: 24.99,
    image: "/vercel.svg",
    description: "100% organic cotton t-shirt, available in multiple colors.",
    category: "Clothing",
  },
  {
    id: 4,
    name: "Running Shoes",
    price: 89.99,
    image: "/window.svg",
    description: "Lightweight running shoes with excellent grip.",
    category: "Footwear",
  },
  {
    id: 5,
    name: "Coffee Mug",
    price: 12.99,
    image: "/globe.svg",
    description: "Ceramic mug, 12oz capacity, microwave safe.",
    category: "Home",
  },
  {
    id: 6,
    name: "Backpack",
    price: 49.99,
    image: "/file.svg",
    description: "Durable backpack with multiple compartments.",
    category: "Accessories",
  },
];
